import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext(null)

export const translations = {
  en: {
    // Navbar
    search_placeholder: 'Search for products...',
    cart: 'Cart',
    wishlist: 'Wishlist',
    my_orders: 'My Orders',
    home: 'Home',
    all: 'All',
    all_categories: 'All Categories',
    categories: 'Categories',
    // Categories
    perfumes: 'Perfumes',
    makeup: 'Makeup',
    hair_care: 'Hair Care',
    body_care: 'Body Care',
    personal_care: 'Personal Care',
    // HomePage
    free_delivery: 'Free Delivery',
    free_delivery_sub: 'On orders over KD 10',
    authentic: '100% Authentic',
    authentic_sub: 'Verified products only',
    same_day: 'Same-Day Delivery',
    same_day_sub: 'Order before 2PM',
    cash_on_delivery: 'Cash on Delivery',
    cash_on_delivery_sub: 'Pay when you receive',
    shop_now: 'Shop Now',
    view_all: 'View All',
    new_arrivals: 'New Arrivals',
    best_sellers: 'Best Sellers',
    deals: 'Deals',
    summer_sale: 'Summer Sale',
    top_perfumes: 'Top Perfumes',
    shop_by_category: 'Shop by Category',
    show_all: 'Show All',
    luxury_perfumes: 'Luxury Perfumes',
    luxury_perfumes_sub: 'Over 1,000 authentic fragrances from top global brands',
    exclusively_zosouq: 'Exclusively on Zosouq',
    premium_makeup: 'Premium Makeup',
    premium_makeup_sub: 'Beauty essentials for every skin tone and occasion',
    new_collection: 'New Collection',
    body_care_essentials: 'Body Care Essentials',
    body_care_essentials_sub: 'Nourish, restore, and glow with premium treatments',
    free_over_10: 'Free over KD 10',
    verified_products: 'Verified products',
    easy_returns: 'Easy Returns',
    easy_returns_sub: '14-day hassle-free',
    support_24_7: '24/7 Support',
    support_sub: 'We are here to help',
    most_loved: 'Most loved by our customers',
    shop_by_price: 'Shop by Price',
    under: 'Under',
    exclusive_deals: 'Exclusive Deals',
    perfume_sale_title: 'Luxury Perfumes at Unbeatable Prices',
    shop_the_sale: 'Shop the Sale',
    up_to_70_off: 'UP TO 70% OFF',
    new_season: 'NEW SEASON',
    fresh_arrivals: 'Fresh Arrivals',
    hair_care_essentials: 'Hair Care Essentials',
    browse_collection: 'Browse Collection',
    latest_additions: 'The latest additions to our collection',
    delivery_banner_title: 'Same-Day Delivery\nAnywhere in Kuwait',
    delivery_banner_description: 'Order today, receive today. Free delivery on orders over KD 10. Cash on delivery available.',
    all_kuwait_areas: 'All Kuwait Areas',
    top_selling_perfumes: 'Top Selling Perfumes',
    popular_fragrances: 'Most popular fragrances in Kuwait',
    exclusive_collection: 'Exclusive Collection',
    luxury_under_one_roof: 'Luxury Perfumes\nUnder One Roof',
    authentic_fragrances: 'Authentic fragrances from Arabian and international brands.',
    explore_collection: 'Explore Collection',
    trending_now: 'Trending Now',
    trending_sub: 'What everyone is adding to their cart',
    flash_sale: 'FLASH SALE',
    makeup_sale_title: 'Up to 50% Off\nPremium Makeup',
    makeup_sale_description: 'Limited time only. Foundation, lipstick, eyeshadow and more.',
    limited_time_offers: 'Limited Time Offers',
    handpicked_for_you: 'Handpicked For You',
    products: 'Products',
    products_found: '{n} products found',
    product_found: '{n} product found',
    browse: 'Browse',
    shop: 'Shop',
    quick_browse: 'Quick Browse',
    quick_browse_sub: 'Jump straight to what you need',
    why_shop: 'Why Shop with Zosouq?',
    why_shop_sub: 'Trusted by thousands of customers across Kuwait',
    all_across_kuwait: 'All across Kuwait',
    guaranteed_genuine: 'Guaranteed genuine',
    delivered_today: 'Delivered today',
    huge_selection: 'Huge selection',
    products_4400: '4,400+ Products',
    categories_count: '{categories} Categories · 4,400+ Products',
    categories_intro: 'From luxurious perfumes to everyday essentials, find exactly what you need.',
    browse_category: 'Browse {category}',
    products_available: '{n} products available',
    filters: 'Filters',
    sort: 'Sort',
    sort_default: 'Default',
    price_low_high: 'Price: Low to High',
    price_high_low: 'Price: High to Low',
    top_rated: 'Top Rated',
    max_price: 'Max Price (KD)',
    clear: 'Clear',
    no_products: 'No products found',
    adjust_filters: 'Try adjusting your filters or browse another category.',
    back_home: 'Back to Home',
    browse_all: 'Browse All',
    cant_find: "Can't find what you need?",
    cant_find_sub: "Chat with us and we'll help you find the perfect product.",
    collection: 'Collection',
    search_products: 'Search Products',
    products_under: 'Products Under {price} KWD',
    results_for: 'Results for "{query}"',
    use_search: 'Use the search bar above to find products.',
    no_results_detail: 'We could not find anything for "{query}". Try different keywords.',
    no_products_under: 'No products found under {price} KWD.',
    browse_all_products: 'Browse All Products',
    wishlist_empty: 'Your Wishlist is Empty',
    wishlist_empty_sub: 'Tap the heart icon on any product to save it here.',
    my_wishlist: 'My Wishlist',
    wishlist_sub: 'Your curated collection of favorites, ready to shop whenever you are.',
    in_wishlist: '{n} items in your wishlist',
    saving: 'Saving',
    move_all_cart: 'Move All to Cart',
    move_all: 'Move All',
    clear_all: 'Clear All',
    move_to_cart: 'Move to Cart',
    removed_wishlist: 'removed from wishlist',
    moved_cart: 'moved to cart',
    wishlist_cleared: 'Wishlist cleared',
    sold_out: 'Sold Out',
    track_orders: 'Track your orders by entering your email address or order number',
    search_by_email: 'Search by Email',
    search_by_order: 'Search by Order #',
    enter_email: 'Enter your email address',
    enter_valid_email: 'Please enter a valid email address',
    enter_order_number: 'Please enter an order number',
    something_wrong: 'Something went wrong. Please try again.',
    search: 'Search',
    no_orders: 'No orders found',
    no_orders_email: 'We could not find any orders with this email address.',
    no_orders_number: 'We could not find an order with this number.',
    orders_found: '{n} orders found',
    pending: 'Pending',
    processing: 'Processing',
    confirmed: 'Confirmed',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    order_placed: 'Order Placed',
    order_confirmed: 'Order Confirmed!',
    order_received: 'Your order has been received.',
    thank_you: 'Thank you, {name}!',
    copy: 'Copy',
    order_status: 'Order Status',
    estimated_delivery: 'Estimated delivery',
    today: 'Today',
    items_ordered: 'Items Ordered',
    qty: 'Qty',
    delivery_details: 'Delivery Details',
    name: 'Name',
    payment: 'Payment',
    continue_shopping: 'Continue Shopping',
    order_not_found: 'Order not found',
    go_home: 'Go Home',
    page_not_found: 'Page not found',
    page_not_found_sub: 'The page you are looking for does not exist or may have been moved.',
    go_back: 'Go Back',
    links: 'Links',
    footer_description: "Kuwait's trusted destination for authentic beauty, skincare and fragrances.",
    kuwait_city: 'Kuwait City',
    same_day_announcement: 'Same-Day Delivery across Kuwait — Free on Orders over KD 10',
    this_weeks_deals: "This Week's Deals",
    explore_categories: 'Explore Categories',
    featured_products: 'Featured Products',
    // ProductCard
    add_to_cart: 'Add to Cart',
    out_of_stock: 'Out of Stock',
    off: 'OFF',
    // ProductPage
    in_stock: 'In Stock',
    low_stock: 'Only {n} left',
    buy_now: 'Buy Now',
    added_to_cart: 'Added to cart',
    quantity: 'Quantity',
    description: 'Description',
    you_may_like: 'You May Also Like',
    product_not_found: 'Product Not Found',
    product_not_found_sub: 'This product may have been removed or the link is incorrect.',
    reviews: 'Reviews',
    save_percent: 'Save {percent}%',
    added: 'Added!',
    saved_wishlist: 'Saved to Wishlist',
    add_wishlist: 'Add to Wishlist',
    added_wishlist: 'added to wishlist',
    write_review: 'Write a Review',
    your_name: 'Your name *',
    share_experience: 'Share your experience (optional)...',
    submit_review: 'Submit Review',
    submitting: 'Submitting...',
    review_thanks: 'Thank you for your review!',
    review_thanks_sub: 'Your feedback helps other shoppers.',
    no_reviews: 'No reviews yet — be the first!',
    more_from: 'More from {category}',
    // Cart
    your_cart: 'Your Cart',
    cart_empty: 'Your Cart is Empty',
    cart_empty_sub: "Looks like you haven't added anything yet.",
    start_shopping: 'Start Shopping',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'FREE',
    total: 'Total',
    proceed_checkout: 'Proceed to Checkout',
    remove: 'Remove',
    // Checkout
    checkout: 'Checkout',
    full_name: 'Full Name',
    phone: 'Phone Number',
    email: 'Email Address',
    address: 'Delivery Address',
    city: 'City / Area',
    notes: 'Order Notes (optional)',
    place_order: 'Place Order',
    order_summary: 'Order Summary',
    nothing_checkout: 'Nothing to Checkout',
    nothing_checkout_sub: 'Your cart is empty. Add some products first!',
    back_to_cart: 'Back to Cart',
    contact_information: 'Contact Information',
    contact_information_sub: 'How can we reach you about your order?',
    enter_full_name: 'Enter your full name',
    delivery_address_sub: 'Where should we deliver your order?',
    governorate: 'Governorate',
    area_city: 'Area / City',
    select_governorate: 'Select or type governorate',
    select_area: 'Select or type area',
    block: 'Block',
    street: 'Street',
    avenue: 'Avenue',
    optional: 'optional',
    house_building: 'House / Building No.',
    floor_apartment: 'Floor / Apt No.',
    order_notes: 'Order Notes',
    delivery_instructions: 'Any special delivery instructions or requests...',
    payment_method: 'Payment Method',
    payment_method_sub: 'How would you like to pay?',
    selected: 'Selected',
    pay_on_arrival: 'Pay cash when your order arrives at your door',
    no_advance_payment: 'No advance payment needed. Pay when items are delivered.',
    view_order_summary: 'View Order Summary',
    summary_shown: 'Summary shown below',
    in_your_order: '{n} items in your order',
    placing_order: 'Placing Order...',
    secure_checkout: 'Secure checkout · Same-day delivery · Cash on delivery',
    edit_cart: 'Edit Cart',
    inclusive_taxes: 'Inclusive of all taxes',
    clear_cart: 'Clear cart',
    cart_cleared: 'Cart cleared',
    each: 'each',
    add_more_shipping: 'Add {amount} more for free shipping',
    // Orders
    my_orders_title: 'My Orders',
    order_number: 'Order',
    // Search
    search_results: 'Search Results',
    no_results: 'No results found',
    search_for: 'Results for',
    // General
    loading: 'Loading...',
    back: 'Back',
    close: 'Close',
    items: 'items',
    item: 'item',
    kd: 'KD',
  },
  ar: {
    // Navbar
    search_placeholder: 'ابحث عن المنتجات...',
    cart: 'السلة',
    wishlist: 'المفضلة',
    my_orders: 'طلباتي',
    home: 'الرئيسية',
    all: 'الكل',
    all_categories: 'جميع الفئات',
    categories: 'الفئات',
    // Categories
    perfumes: 'العطور',
    makeup: 'المكياج',
    hair_care: 'العناية بالشعر',
    body_care: 'العناية بالجسم',
    personal_care: 'العناية الشخصية',
    // HomePage
    free_delivery: 'توصيل مجاني',
    free_delivery_sub: 'للطلبات فوق ١٠ دينار',
    authentic: '١٠٠٪ أصلي',
    authentic_sub: 'منتجات موثقة فقط',
    same_day: 'توصيل في نفس اليوم',
    same_day_sub: 'اطلب قبل الساعة ٢ ظهراً',
    cash_on_delivery: 'الدفع عند الاستلام',
    cash_on_delivery_sub: 'ادفع عند وصول الطلب',
    shop_now: 'تسوق الآن',
    view_all: 'عرض الكل',
    new_arrivals: 'وصل حديثاً',
    best_sellers: 'الأكثر مبيعاً',
    deals: 'العروض',
    summer_sale: 'تخفيضات الصيف',
    top_perfumes: 'أفضل العطور',
    shop_by_category: 'تسوق حسب الفئة',
    show_all: 'عرض الكل',
    luxury_perfumes: 'عطور فاخرة',
    luxury_perfumes_sub: 'أكثر من ١٠٠٠ عطر أصلي من أشهر العلامات العالمية',
    exclusively_zosouq: 'حصرياً على زوسوق',
    premium_makeup: 'مكياج فاخر',
    premium_makeup_sub: 'مستلزمات تجميل لكل لون بشرة وكل مناسبة',
    new_collection: 'تشكيلة جديدة',
    body_care_essentials: 'أساسيات العناية بالجسم',
    body_care_essentials_sub: 'غذّي بشرتك واستعيدي إشراقتها بعلاجات فاخرة',
    free_over_10: 'مجاني للطلبات فوق ١٠ د.ك',
    verified_products: 'منتجات أصلية موثقة',
    easy_returns: 'إرجاع سهل',
    easy_returns_sub: 'إرجاع ميسر خلال ١٤ يوماً',
    support_24_7: 'دعم على مدار الساعة',
    support_sub: 'نحن هنا لمساعدتك',
    most_loved: 'المنتجات الأكثر محبة لدى عملائنا',
    shop_by_price: 'تسوق حسب السعر',
    under: 'أقل من',
    exclusive_deals: 'عروض حصرية',
    perfume_sale_title: 'عطور فاخرة بأسعار لا تقاوم',
    shop_the_sale: 'تسوق العروض',
    up_to_70_off: 'خصم يصل إلى ٧٠٪',
    new_season: 'موسم جديد',
    fresh_arrivals: 'وصل حديثاً',
    hair_care_essentials: 'أساسيات العناية بالشعر',
    browse_collection: 'تصفح المجموعة',
    latest_additions: 'أحدث الإضافات إلى مجموعتنا',
    delivery_banner_title: 'توصيل في نفس اليوم\nإلى جميع مناطق الكويت',
    delivery_banner_description: 'اطلب اليوم واستلم اليوم. توصيل مجاني للطلبات فوق ١٠ د.ك، والدفع عند الاستلام متاح.',
    all_kuwait_areas: 'جميع مناطق الكويت',
    top_selling_perfumes: 'العطور الأكثر مبيعاً',
    popular_fragrances: 'العطور الأكثر رواجاً في الكويت',
    exclusive_collection: 'مجموعة حصرية',
    luxury_under_one_roof: 'عطور فاخرة\nفي مكان واحد',
    authentic_fragrances: 'عطور أصلية من العلامات العربية والعالمية.',
    explore_collection: 'استكشف المجموعة',
    trending_now: 'الأكثر رواجاً الآن',
    trending_sub: 'المنتجات التي يضيفها الجميع إلى سلتهم',
    flash_sale: 'تخفيضات سريعة',
    makeup_sale_title: 'خصم يصل إلى ٥٠٪\nعلى المكياج الفاخر',
    makeup_sale_description: 'لفترة محدودة فقط. كريم أساس وأحمر شفاه وظلال عيون والمزيد.',
    limited_time_offers: 'عروض لفترة محدودة',
    handpicked_for_you: 'مختاراتنا لك',
    products: 'منتجات',
    products_found: 'تم العثور على {n} منتجات',
    product_found: 'تم العثور على منتج واحد',
    browse: 'تصفح',
    shop: 'تسوق',
    quick_browse: 'تصفح سريع',
    quick_browse_sub: 'انتقل مباشرة إلى ما تحتاجه',
    why_shop: 'لماذا تتسوق من زوسوق؟',
    why_shop_sub: 'موثوق به من آلاف العملاء في الكويت',
    all_across_kuwait: 'في جميع أنحاء الكويت',
    guaranteed_genuine: 'أصلي مضمون',
    delivered_today: 'يصلك اليوم',
    huge_selection: 'تشكيلة واسعة',
    products_4400: 'أكثر من ٤٤٠٠ منتج',
    categories_count: '{categories} فئات · أكثر من ٤٤٠٠ منتج',
    categories_intro: 'من العطور الفاخرة إلى الاحتياجات اليومية، اعثر على كل ما تحتاجه.',
    browse_category: 'تصفح {category}',
    products_available: '{n} منتج متوفر',
    filters: 'التصفية',
    sort: 'الترتيب',
    sort_default: 'الافتراضي',
    price_low_high: 'السعر: من الأقل إلى الأعلى',
    price_high_low: 'السعر: من الأعلى إلى الأقل',
    top_rated: 'الأعلى تقييماً',
    max_price: 'أعلى سعر (د.ك)',
    clear: 'مسح',
    no_products: 'لا توجد منتجات',
    adjust_filters: 'جرّب تعديل عوامل التصفية أو تصفح فئة أخرى.',
    back_home: 'العودة للرئيسية',
    browse_all: 'تصفح الكل',
    cant_find: 'لم تجد ما تبحث عنه؟',
    cant_find_sub: 'تواصل معنا وسنساعدك في العثور على المنتج المناسب.',
    collection: 'المجموعة',
    search_products: 'البحث عن المنتجات',
    products_under: 'منتجات بأقل من {price} د.ك',
    results_for: 'نتائج البحث عن "{query}"',
    use_search: 'استخدم شريط البحث أعلاه للعثور على المنتجات.',
    no_results_detail: 'لم نجد نتائج عن "{query}". جرّب كلمات أخرى.',
    no_products_under: 'لا توجد منتجات بأقل من {price} د.ك.',
    browse_all_products: 'تصفح جميع المنتجات',
    wishlist_empty: 'قائمة المفضلة فارغة',
    wishlist_empty_sub: 'اضغط على رمز القلب في أي منتج لحفظه هنا.',
    my_wishlist: 'قائمة المفضلة',
    wishlist_sub: 'مجموعتك المختارة من المنتجات المفضلة جاهزة للتسوق.',
    in_wishlist: '{n} منتجات في المفضلة',
    saving: 'التوفير',
    move_all_cart: 'نقل الكل إلى السلة',
    move_all: 'نقل الكل',
    clear_all: 'مسح الكل',
    move_to_cart: 'نقل إلى السلة',
    removed_wishlist: 'تمت إزالته من المفضلة',
    moved_cart: 'تم نقله إلى السلة',
    wishlist_cleared: 'تم مسح المفضلة',
    sold_out: 'نفد المخزون',
    track_orders: 'تتبع طلباتك باستخدام البريد الإلكتروني أو رقم الطلب',
    search_by_email: 'البحث بالبريد الإلكتروني',
    search_by_order: 'البحث برقم الطلب',
    enter_email: 'أدخل بريدك الإلكتروني',
    enter_valid_email: 'يرجى إدخال بريد إلكتروني صحيح',
    enter_order_number: 'يرجى إدخال رقم الطلب',
    something_wrong: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    search: 'بحث',
    no_orders: 'لا توجد طلبات',
    no_orders_email: 'لم نجد أي طلبات مرتبطة بهذا البريد الإلكتروني.',
    no_orders_number: 'لم نجد طلباً بهذا الرقم.',
    orders_found: 'تم العثور على {n} طلبات',
    pending: 'قيد الانتظار',
    processing: 'قيد التجهيز',
    confirmed: 'تم التأكيد',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'ملغي',
    order_placed: 'تم تقديم الطلب',
    order_confirmed: 'تم تأكيد الطلب!',
    order_received: 'تم استلام طلبك.',
    thank_you: 'شكراً لك، {name}!',
    copy: 'نسخ',
    order_status: 'حالة الطلب',
    estimated_delivery: 'موعد التوصيل المتوقع',
    today: 'اليوم',
    items_ordered: 'المنتجات المطلوبة',
    qty: 'الكمية',
    delivery_details: 'تفاصيل التوصيل',
    name: 'الاسم',
    payment: 'الدفع',
    continue_shopping: 'متابعة التسوق',
    order_not_found: 'لم يتم العثور على الطلب',
    go_home: 'الذهاب للرئيسية',
    page_not_found: 'الصفحة غير موجودة',
    page_not_found_sub: 'الصفحة التي تبحث عنها غير موجودة أو ربما تم نقلها.',
    go_back: 'رجوع',
    links: 'الروابط',
    footer_description: 'وجهتك الموثوقة في الكويت لمنتجات الجمال والعناية والعطور الأصلية.',
    kuwait_city: 'مدينة الكويت',
    same_day_announcement: 'توصيل في نفس اليوم داخل الكويت — مجاناً للطلبات فوق ١٠ د.ك',
    this_weeks_deals: 'عروض هذا الأسبوع',
    explore_categories: 'استكشف الفئات',
    featured_products: 'منتجات مميزة',
    // ProductCard
    add_to_cart: 'أضف إلى السلة',
    out_of_stock: 'نفد المخزون',
    off: 'خصم',
    // ProductPage
    in_stock: 'متوفر',
    low_stock: 'متبقي {n} فقط',
    buy_now: 'اشتر الآن',
    added_to_cart: 'تمت الإضافة إلى السلة',
    quantity: 'الكمية',
    description: 'الوصف',
    you_may_like: 'قد يعجبك أيضاً',
    product_not_found: 'المنتج غير موجود',
    product_not_found_sub: 'ربما تمت إزالة هذا المنتج أو أن الرابط غير صحيح.',
    reviews: 'التقييمات',
    save_percent: 'وفر {percent}٪',
    added: 'تمت الإضافة!',
    saved_wishlist: 'محفوظ في المفضلة',
    add_wishlist: 'أضف إلى المفضلة',
    added_wishlist: 'تمت إضافته إلى المفضلة',
    write_review: 'اكتب تقييماً',
    your_name: 'اسمك *',
    share_experience: 'شارك تجربتك (اختياري)...',
    submit_review: 'إرسال التقييم',
    submitting: 'جارٍ الإرسال...',
    review_thanks: 'شكراً لتقييمك!',
    review_thanks_sub: 'ملاحظاتك تساعد المتسوقين الآخرين.',
    no_reviews: 'لا توجد تقييمات بعد — كن الأول!',
    more_from: 'المزيد من {category}',
    // Cart
    your_cart: 'سلة التسوق',
    cart_empty: 'سلتك فارغة',
    cart_empty_sub: 'يبدو أنك لم تضف أي منتجات بعد.',
    start_shopping: 'ابدأ التسوق',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    free: 'مجاني',
    total: 'الإجمالي',
    proceed_checkout: 'إتمام الشراء',
    remove: 'حذف',
    // Checkout
    checkout: 'إتمام الطلب',
    full_name: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    address: 'عنوان التوصيل',
    city: 'المدينة / المنطقة',
    notes: 'ملاحظات الطلب (اختياري)',
    place_order: 'تأكيد الطلب',
    order_summary: 'ملخص الطلب',
    nothing_checkout: 'لا توجد منتجات لإتمام الطلب',
    nothing_checkout_sub: 'سلتك فارغة. أضف بعض المنتجات أولاً!',
    back_to_cart: 'العودة إلى السلة',
    contact_information: 'معلومات التواصل',
    contact_information_sub: 'كيف يمكننا التواصل معك بخصوص طلبك؟',
    enter_full_name: 'أدخل اسمك الكامل',
    delivery_address_sub: 'أين تريد توصيل طلبك؟',
    governorate: 'المحافظة',
    area_city: 'المنطقة / المدينة',
    select_governorate: 'اختر أو اكتب المحافظة',
    select_area: 'اختر أو اكتب المنطقة',
    block: 'القطعة',
    street: 'الشارع',
    avenue: 'الجادة',
    optional: 'اختياري',
    house_building: 'رقم المنزل / المبنى',
    floor_apartment: 'الطابق / رقم الشقة',
    order_notes: 'ملاحظات الطلب',
    delivery_instructions: 'أي تعليمات أو طلبات خاصة للتوصيل...',
    payment_method: 'طريقة الدفع',
    payment_method_sub: 'كيف تود الدفع؟',
    selected: 'محدد',
    pay_on_arrival: 'ادفع نقداً عند وصول طلبك',
    no_advance_payment: 'لا حاجة للدفع مقدماً. ادفع عند استلام المنتجات.',
    view_order_summary: 'عرض ملخص الطلب',
    summary_shown: 'الملخص ظاهر أدناه',
    in_your_order: '{n} منتجات في طلبك',
    placing_order: 'جارٍ تقديم الطلب...',
    secure_checkout: 'دفع آمن · توصيل في نفس اليوم · الدفع عند الاستلام',
    edit_cart: 'تعديل السلة',
    inclusive_taxes: 'شامل جميع الضرائب',
    clear_cart: 'مسح السلة',
    cart_cleared: 'تم مسح السلة',
    each: 'للقطعة',
    add_more_shipping: 'أضف {amount} للحصول على توصيل مجاني',
    // Orders
    my_orders_title: 'طلباتي',
    order_number: 'طلب',
    // Search
    search_results: 'نتائج البحث',
    no_results: 'لا توجد نتائج',
    search_for: 'نتائج عن',
    // General
    loading: 'جاري التحميل...',
    back: 'رجوع',
    close: 'إغلاق',
    items: 'منتجات',
    item: 'منتج',
    kd: 'د.ك',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en')

  useEffect(() => {
    localStorage.setItem('lang', lang)
    // Set dir on body (NOT html) — setting it on html breaks position:sticky on mobile
    document.body.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
    if (lang === 'ar') {
      document.documentElement.classList.add('rtl')
    } else {
      document.documentElement.classList.remove('rtl')
    }
  }, [lang])

  const t = (key, vars = {}) => {
    let str = translations[lang]?.[key] || translations.en[key] || key
    Object.entries(vars).forEach(([k, v]) => { str = str.replace(`{${k}}`, v) })
    return str
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL: lang === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
